# Generated by Django 6.1.1 on 2026-09-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, unique=True)),
                ('payment_status', models.CharField(blank=True, max_length=32)),
                ('shipment_status', models.CharField(blank=True, max_length=32)),
                ('amount_paise', models.BigIntegerField(null=True)),
                ('payment_updated_at', models.DateTimeField(null=True)),
                ('shipment_updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('missing_locally', 'Missing Locally'), ('status_mismatch', 'Status Mismatch'), ('amount_mismatch', 'Amount Mismatch')], max_length=32)),
                ('local_value', models.CharField(blank=True, max_length=64)),
                ('provider_value', models.CharField(blank=True, max_length=64)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('event_id', models.CharField(help_text="Provider's id, or a hash of the body: the idempotency key", max_length=128)),
                ('event_type', models.CharField(max_length=64)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('occurred_at', models.DateTimeField(help_text='When the provider says it happened (for ordering)', null=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('dead_letter', 'Dead Letter')], db_index=True, default='received', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_provider_event')],
            },
        ),
    ]
